### ISSUE TITLE
initial milestone

### ISSUE THREAD

**Issue by omouse** [omouse/angular-seed#1]
Things that need to work for a basic project to work:
- [ ] common rollup config
- [ ] rollup config for vendor bundle
- [ ] rollup config for jit
- [ ] rollup config for aot
- [ ] end2end tests using karma and chrome
- [ ] end2end tests using karma and firefox
- [ ] liteserver configuration
- [ ] watches for changes and re-compiles
